version: "3.9"

services:
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/backend/app
      - .env:/backend/.env
    working_dir: /backend

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wanted_db
    command: >
      --default-authentication-plugin=caching_sha2_password
      --ngram_token_size=2
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
