# ruff: noqa
# mypy: ignore-errors
"""
empty message

Revision ID: 4571299ee188
Revises: 659c59631060
Create Date: 2025-06-25 22:50:39.044951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4571299ee188'
down_revision: Union[str, Sequence[str], None] = '659c59631060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_tag', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('company_tag', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_companytag_created_at', 'company_tag', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_companytag_created_at', table_name='company_tag')
    op.drop_column('company_tag', 'updated_at')
    op.drop_column('company_tag', 'created_at')
    # ### end Alembic commands ###
