# ruff: noqa
# mypy: ignore-errors
"""
empty message

Revision ID: 659c59631060
Revises: af3d88b87c7e
Create Date: 2025-06-25 19:15:01.087998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '659c59631060'
down_revision: Union[str, Sequence[str], None] = 'af3d88b87c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_companyname_name_lang', 'company_name', ['name', 'lang_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_companyname_name_lang', 'company_name', type_='unique')
    # ### end Alembic commands ###
